# Generated by Django 4.2.2 on 2023-09-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fundacion', models.CharField(max_length=20)),
                ('presupuesto', models.IntegerField()),
            ],
        ),
    ]
