# Generated by Django 4.2.2 on 2023-09-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('duracion', models.DurationField()),
                ('recaudacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad_temporadas', models.IntegerField()),
                ('fecha_estreno', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='productora',
            name='fundacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productora',
            name='presupuesto',
            field=models.FloatField(),
        ),
    ]
