# Generated by Django 4.2.2 on 2023-09-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_pelicula_productoracinematografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='productoraCinematografica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.productora'),
            preserve_default=False,
        ),
    ]
