# Generated by Django 4.2.2 on 2023-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_pelicula_nombre_alter_productora_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('agree_terms', models.BooleanField()),
            ],
        ),
    ]
