# Generated by Django 4.2.2 on 2023-09-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_userregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ('user',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_id',
            new_name='user',
        ),
    ]
