# Generated by Django 4.2.2 on 2023-10-06 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='actores/')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores De Cine',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Accion', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasia', 'Fantasía')], max_length=100)),
            ],
            options={
                'verbose_name': 'Generos',
                'verbose_name_plural': 'Generos De Cine',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reparto',
            field=models.ManyToManyField(to='MyApp.actor'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='tags',
            field=models.ManyToManyField(to='MyApp.tag'),
        ),
    ]
