# Generated by Django 4.2.2 on 2023-10-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_actor_tag_pelicula_descripcion_pelicula_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
