# Generated by Django 4.2.2 on 2023-10-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_pelicula_portada_alter_pelicula_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
