# Generated by Django 4.2.2 on 2023-10-08 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='descripcion',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AddField(
            model_name='serie',
            name='portada',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='serie',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='reparto',
            field=models.ManyToManyField(to='MyApp.actor'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tags',
            field=models.ManyToManyField(to='MyApp.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(choices=[('Accion', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasia', 'Fantasía'), ('Animacion', 'Animacion'), ('Terror', 'Terror'), ('Thriller', 'Thriller'), ('Suspenso', 'Suspenso'), ('Sci-Fi', 'Sci-Fi')], max_length=100),
        ),
    ]
