# Generated by Django 4.2.2 on 2023-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
