# Generated by Django 4.2.2 on 2023-10-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_alter_customuser_agree_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agree_terms',
        ),
    ]
