# Generated by Django 4.2.2 on 2023-10-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_remove_customuser_agree_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=255)),
                ('peliculas', models.ManyToManyField(to='MyApp.pelicula')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Lista De Peliculas',
                'ordering': ('nombre_pelicula',),
            },
        ),
    ]
