# Generated by Django 4.2.2 on 2023-10-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_listapeliculas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='listadepeliculas',
            field=models.ManyToManyField(related_name='usuarios_que_guardaron', to='MyApp.pelicula'),
        ),
    ]
