# Generated by Django 4.2.2 on 2023-10-11 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='descripcion_usuario',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='perfil/'),
        ),
    ]
